import { ToolItem } from "@/types";

export const CATEGORIES = [
  { id: "all", name: "เครื่องมือทั้งหมด", nameEn: "All Tools" },
  { id: "pdf", name: "PDF Tools", nameEn: "PDF Tools", icon: "FileText" },
  { id: "image", name: "Image Tools", nameEn: "Image Tools", icon: "Image" },
  { id: "ai", name: "AI Tools", nameEn: "AI Tools", icon: "Sparkles" },
  { id: "conversion", name: "File Conversion", nameEn: "File Conversion", icon: "RefreshCw" },
] as const;

export const TOOLS: ToolItem[] = [
  // Image Tools
  {
    id: "image-compressor",
    name: "บีบอัดรูปภาพ",
    nameEn: "Image Compressor",
    description: "ลดขนาดไฟล์รูปภาพ PNG, JPG, WebP โดยไม่สูญเสียความคมชัด รวดเร็ว ปลอดภัย",
    category: "image",
    categoryName: "Image Tools",
    iconName: "Minimize2",
    href: "/tools/image-compressor",
    isPopular: true,
    creditCost: 0,
    badge: "ฟรียอดนิยม",
  },
  {
    id: "image-converter",
    name: "แปลงไฟล์รูปภาพ",
    nameEn: "Image Converter",
    description: "แปลงสกุลไฟล์รูปภาพไปมาระหว่าง JPG, PNG, WebP, AVIF อย่างแม่นยำ",
    category: "image",
    categoryName: "Image Tools",
    iconName: "RefreshCw",
    href: "/tools/image-converter",
    isPopular: true,
    creditCost: 0,
  },
  // PDF Tools
  {
    id: "pdf-merger",
    name: "รวมไฟล์ PDF",
    nameEn: "PDF Merger",
    description: "รวมเอกสาร PDF หลายไฟล์เข้าด้วยกันเป็นไฟล์เดียว ลากจัดเรียงหน้าได้ง่ายดาย",
    category: "pdf",
    categoryName: "PDF Tools",
    iconName: "Files",
    href: "/tools/pdf-merger",
    isPopular: true,
    creditCost: 1,
    badge: "ใช้งานง่าย",
  },
  {
    id: "pdf-splitter",
    name: "แยกหน้า PDF",
    nameEn: "PDF Splitter",
    description: "แยกหน้าเอกสาร PDF หรือเลือกดึงเฉพาะหน้าที่ต้องการได้อย่างอิสระ",
    category: "pdf",
    categoryName: "PDF Tools",
    iconName: "Scissors",
    href: "/tools/pdf-merger", // routes to pdf studio placeholder
    creditCost: 1,
  },
  // AI Tools
  {
    id: "ai-thai-refiner",
    name: "AI ขัดเกลาภาษาไทย",
    nameEn: "AI Thai Refiner",
    description: "ปรับโทนข้อความภาษาไทยให้ทางการ สุภาพ เขียนแคปชั่น หรือปรับให้กระชับสละสลวย",
    category: "ai",
    categoryName: "AI Tools",
    iconName: "Sparkles",
    href: "/tools/ai-thai-refiner",
    isPopular: true,
    creditCost: 2,
    badge: "AI อัจฉริยะ",
  },
  {
    id: "ai-summarizer",
    name: "AI สรุปเอกสาร",
    nameEn: "AI Document Summarizer",
    description: "สรุปใจความสำคัญจากบทความ ยาวๆ ให้เหลือประเด็นหลักในไม่กี่วินาที",
    category: "ai",
    categoryName: "AI Tools",
    iconName: "BookOpen",
    href: "/tools/ai-thai-refiner",
    creditCost: 2,
  },
  // File Conversion
  {
    id: "file-to-pdf",
    name: "แปลงไฟล์เป็น PDF",
    nameEn: "Convert to PDF",
    description: "แปลงรูปภาพและเอกสารหลากหลายชนิดให้อยู่ในรูปแบบ PDF มาตรฐาน",
    category: "conversion",
    categoryName: "File Conversion",
    iconName: "FileUp",
    href: "/tools/image-converter",
    creditCost: 1,
  },
  {
    id: "pdf-to-image",
    name: "แปลง PDF เป็นรูปภาพ",
    nameEn: "PDF to Image",
    description: "แปลงหน้าเอกสาร PDF ทุกหน้าให้เป็นไฟล์รูปภาพ PNG หรือ JPG ความละเอียดสูง",
    category: "conversion",
    categoryName: "File Conversion",
    iconName: "ImageDown",
    href: "/tools/image-converter",
    creditCost: 1,
  },
];
